stages:
  - test

component_test:
  stage: test
  image: mcr.microsoft.com/playwright:v1.59.1-noble
  script:
    - npm ci
    - npx playwright test
  artifacts:
    when: always
    paths:
      - playwright-reports
    expire_in: 2 days  